name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - run: python --version

      - run: pip install -U pytest
      - run: pip install -r pipeline_project/requirements.pokedex.txt

      - run: cd pipeline_project
      - run: ls -R

      - run: cd pipeline_project
      - run: pytest